export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  donorDashboard: '/donor/dashboard',
  postDonation: '/donor/post-donation',
  myDonations: '/donor/my-donations',
  donationHistory: '/donor/donation-history',
  donorProfile: '/donor/profile',
  notifications: '/donor/notifications',
  ngoDashboard: '/ngo/dashboard',
  ngoAvailableDonations: '/ngo/available-donations',
  ngoRequests: '/ngo/requests',
  ngoBookedDonations: '/ngo/booked-donations',
  ngoHistory: '/ngo/history',
  ngoNotifications: '/ngo/notifications',
  donorRegister: '/register?role=donor',
  ngoRegister: '/register?role=ngo',
};
